### ISSUE TITLE
CSS should use variables to pick between light and dark mode

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#199]
The CSS files should use `var`s to dispatch colours.

`:root` would have the default palette, light:

```css
:root {
	--background-colour: …;
	--text-colour: …;
	--link-colour: …;
}
```

and `html` would be like this:

```css
html[data-theme='light'] {
    --background-colour: …;
    --text-colour: …;
    --link-color: …;
}

html[data-theme='dark'] {
    --background-colour: …;
    --text-colour: …;
    --link-colour: …;
}
```

The JS should be changed to take the user preferences into account.

Ref: https://lukelowrey.com/css-variable-theme-switcher/
