### ISSUE TITLE
Better categories model for Flora

### ISSUE THREAD

**Issue by tchoutri** [flora-pm/flora-server#26]
In the same vein as https://lib.rs, we have a shot at producing a better category model for the packages that we import. 

## Current situation in Hackage

Many categories are duplicated due to pluralisation, overlap and synonyms. For example:

* Algorithm, Algorithms
* Bit, Bits
* Finance, Financial
* GIS programs, Geospatial, 
* Cryptography, Hash
* CLI, CLI Tool, Command Line, Command Line Tool, Command Line Tools, CommandLine
* None (??)
* Haskell (??)
* Message-Oriented Middleware, Middleware
* Numeric, Numerics, Numerical
* Parser, Parser Builder, Parser Combinators, ParserCombinators, Parsers, Parsing

And so on.

## Fixing this mess

We can adopt lib.rs' strategy of having a canonical source of truth for the categories we allow, written out as a TOML file to improve contributions directly from the code forge interface.

```toml
# [slug]
# name = "Display name"
# synopsis = "One-line description"

[algorithms]
name = "Algorithms"
synopsis = "Algorithms implemented in Haskell, like sorting, searching"

[cryptography]
name = "Cryptography"
synopsis = "Algorithms for encrypting and hashing data"

[distributed]
name = "Distributed Systems & Computation"
synopsis = "Tooling and techniques for writing distributed systems"

[parsers]
name = "Parsers"
synopsis = "Libraries to ingest and parse data"
```

And have a mapping code in the importer from Hackage that would unify all the very-similar categories under one.

---

References:

* https://gitlab.com/crates.rs/crates.rs/-/blob/main/categories/src/categories.toml
* https://gitlab.com/crates.rs/crates.rs/-/blob/main/categories/src/tuning.rs
* https://gitlab.com/crates.rs/crates.rs/-/blob/main/categories/src/categories.rs
